export const environment = {
  name: 'qa',
  production: true,
  authToken: 'ba19d949-90a3-3b37-9eb8-7f4f67e7caba',
  tokenURL: 'https://testapigateway.upexciseonline.co/token/',
  consumerKey: 'wm8ZarwKn2UZ8tZQpqDCarzXUnwa',
  consumerSecret: 'v4AOZnFxUH492bG9TOHOnuqRZOAa',
  tokenUsername: 'admin',
  tokenPassword: 'Adm9jsd32',
  baseURLMaster: 'https://testapigateway.upexciseonline.co/master/v1.0.0/',
  baseURL: 'https://testapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  jsonBaseURL: 'https://json.upexciseonline.co/',
  baseURLUser: 'https://testapigateway.upexciseonline.co/user-managment/v1.0.0/',
  sugarmillBaseURL: 'https://testapigateway.upexciseonline.co/sugarmill/v1.0.0/',
  distilleryBaseURL: 'https://testapigateway.upexciseonline.co/distillery/v1.0.0/',
  localDBUrl: 'https://json.upexciseonline.co/',
  licencemanagementURL: 'https://testapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
  wholesaleURL: 'https://testapigateway.upexciseonline.co/wholesale/1.0.0/',
  warehouseURL: 'https://testapigateway.upexciseonline.co/warehouse/1.0.0/',
  warehouseurl: 'https://testapigateway.upexciseonline.co/warehouse/1.0.0/',
  // helpdeskURL: 'https://testapigateway.upexciseonline.co/helpdesk/v1.0.0/',
  // retailURL: 'https://testapigateway.upexciseonline.co/retailpos/v1.0.0/',
  workflowconfig: 'https://testapigateway.upexciseonline.co/workflow/v1.0.0/',
  devisionUrl: 'https://testapigateway.upexciseonline.co/master/v1.0.0/',
  documentIPUrl: 'https://testapigateway.upexciseonline.co/docManagement/v1.0.0/',
  documentUrl: 'https://testapigateway.upexciseonline.co/docManagement/v1.0.0/',
  licencemanagementIPURL: 'https://testapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
  wholesaledevURL: 'https://testapigateway.upexciseonline.co/wholesale/1.0.0/',
  userManagerUrl: 'https://testapigateway.upexciseonline.co/userManagement/',
  worflowIPURL: 'https://testapigateway.upexciseonline.co/workflow/v1.0.0/',
  parentunit: 'https://testapigateway.upexciseonline.co/parentUnit/1.0/',
  parentUnit: 'https://testapigateway.upexciseonline.co/parentUnit/1.0/',
  notificationURL: 'https://testapigateway.upexciseonline.co/notification/v1.0.0/',
  helpdesk: 'https://testapigateway.upexciseonline.co/helpdesk/',
  wareHouse: "https://testapigateway.upexciseonline.co/warehouse/",
  baseURLMasterIpAddr: 'https://testapigateway.upexciseonline.co/masterData/',
  baseURLL: 'https://testapigateway.upexciseonline.co/masterData/',
  scmproduction: 'http://devapigateway.upexciseonline.co/scmProduction/v1.0.0/',
  MasterBaseUrl: 'https://devapigateway.upexciseonline.co/master/v1.0.0/',
  basemasterDataURLL: 'http://65.0.150.210:3503/masterData/',
  licneseBaseUrl: 'https://devapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
  CommonsearchUrl: 'http://115.124.100.227:8151/scmretailapi/',
  // Sms: 'http://65.0.150.210:3531/',



  Sms: 'https://testapigateway.upexciseonline.co/sms/1.0/',
  // helpdeskURL: 'https://testapigateway.upexciseonline.co/helpdesk/v1.0.0/',
  helpdeskURL: 'http://localhost:3333/helpdesk/',
  registerbaseurl: 'https://testapigateway.upexciseonline.co/user-managment/v1.0.0/',
  uploadBaseurl: 'https://testapigateway.upexciseonline.co/docManagement/v1.0.0/',
  retailURL: 'https://testapigateway.upexciseonline.co/retailpos/v1.0.0/',
  payandreconBaseUrl: 'https://testapigateway.upexciseonline.co/'

};
