export const environment = {
    name: 'stg',
    production: false,
    authToken: '7aaa4d3f-76c8-30db-8f8b-7c75729757ab',
    tokenURL: 'https://stgapigateway.upexciseonline.co/token',
    consumerKey: 'wm8ZarwKn2UZ8tZQpqDCarzXUnwa',
    consumerSecret: 'v4AOZnFxUH492bG9TOHOnuqRZOAa',
    tokenUsername: 'admin',
    tokenPassword: 'Adm9jsd32',
    baseURLMaster: 'https://stgapigateway.upexciseonline.co/master/v1.0.0/',
    baseURL: 'https://stgapigateway.upexciseonline.co/sugarmill/v1.0.0/',
    jsonBaseURL: 'https://json.upexciseonline.co/',
    baseURLUser: 'http://65.0.150.210:3518/userManagement/',
    baseURLL: 'http://65.0.150.210:3503/masterData/',
    basemasterDataURLL: 'http://65.0.150.210:3503/masterData/',
    sugarmillBaseURL: 'https://stgapigateway.upexciseonline.co/sugarmill/v1.0.0/',
    localDBUrl: 'http://localhost:3000/',
    licencemanagementURL: 'https://stgapigateway.upexciseonline.co/licensemanagementnew/v1.0.0/',
    wholesaleURL: 'https://stgapigateway.upexciseonline.co/wholesale/1.0.0/',
    warehouseURL: 'https://stgapigateway.upexciseonline.co/warehouse/1.0.0/',
    warehouseurl: 'https://stgapigateway.upexciseonline.co/warehouse/1.0.0/',
    distilleryBaseURL: 'http://65.0.150.210:3504/distillery/',
    workflowconfig: 'https://stgapigateway.upexciseonline.co/workflow/v1.0.0/',
    devisionUrl: 'http://65.0.150.210:3503/masterData/',
    documentUrl: 'https://stgapigateway.upexciseonline.co/docManagement/v1.0.0/',
    documentIPUrl: 'http://65.0.150.210:3517/docManagement/',
    licencemanagementIPURL: 'http://65.0.150.210:3505/licenseManagement/',
    userManagerUrl: 'https://stgapigateway.upexciseonline.co/user-managment/v1.0.0/',
    worflowIPURL: 'http://65.0.150.210:3516/workflow/',
    parentUnit: 'http://65.0.150.210:3501/scmProduction/',
    helpdesk: 'http://65.0.150.210:3506/helpdesk/',
    notificationURL: 'http://65.0.150.210:3515/notification/',
    baseURLMasterIpAddr: 'http://65.0.150.210:3503/masterData/',

    //brewery changes
    scmproduction: 'http://stgapigateway.upexciseonline.co/scmProduction/v1.0.0/',
    licneseBaseUrl: 'https://stgapigateway.upexciseonline.co/licensemanagement/v1.0.0/',
    MasterBaseUrl: 'https://stgapigateway.upexciseonline.co/master/v1.0.0/',
    CommonsearchUrl: 'http://115.124.100.227:8151/scmretailapi/',


    Sms: 'https://stgapigateway.upexciseonline.co/sms/1.0/',
    helpdeskURL: 'https://stgapigateway.upexciseonline.co/helpdesk/v1.0.0/',
    registerbaseurl: 'https://stgapigateway.upexciseonline.co/user-managment/v1.0.0/',
    uploadBaseurl: 'https://stgapigateway.upexciseonline.co/docManagement/v1.0.0/',
    retailURL: 'https://stgapigateway.upexciseonline.co/retailpos/v1.0.0/',
    payandreconBaseUrl: 'https://stgapigateway.upexciseonline.co/'
};
